pdm-project/pdm-backend

- news/bugfix.17.md
- pdm/pep517/base.py
- tests/test_file_finder.py
Recently I used `pdm build` to build the source distribution file and found out it contains some un-required files such as cache files generated by **mypy**. So I used `excludes = ["**/.mypy_cache"]` from `[tool.pdm]` sections in `pyproject.toml` file. But it doesn't work at all.
I did some digging about the root cause of this problem. The `_find_files_iter` method uses exclude glob patterns to generate directories and files which need to be excluded from the distribution building. But the `_match_path` doesn't consider the scenario of `pattern` as a directory.
> Fix files finding error if the glob result of excludes containing directory.

- README.md
- news/95.feature.md
- pdm/pep517/metadata.py
- pdm/pep517/version.py
- pyproject.toml
- tests/fixtures/projects/demo-cextension-in-src/pyproject.toml
- tests/fixtures/projects/demo-cextension/pyproject.toml
- tests/fixtures/projects/demo-explicit-package-dir/pyproject.toml
- tests/fixtures/projects/demo-module/pyproject.toml
- tests/fixtures/projects/demo-no-license/pyproject.toml
- tests/fixtures/projects/demo-package-include-error/pyproject.toml
- tests/fixtures/projects/demo-package-include-old/pyproject.toml
- tests/fixtures/projects/demo-package-include/pyproject.toml
- tests/fixtures/projects/demo-package-with-deep-path/pyproject.toml
- tests/fixtures/projects/demo-package-with-tests/pyproject.toml
- tests/fixtures/projects/demo-package/pyproject.toml
- tests/fixtures/projects/demo-pep420-package/pyproject.toml
- tests/fixtures/projects/demo-purelib-with-build/pyproject.toml
- tests/fixtures/projects/demo-src-package-include/pyproject.toml
- tests/fixtures/projects/demo-src-package/pyproject.toml
- tests/fixtures/projects/demo-src-pymodule/pyproject.toml
- tests/fixtures/projects/demo-using-scm/pyproject.toml
New version table:
```toml
[tool.pdm.version]
source = "file"
path = "mypackage/__version__.py"
```
OR:
```toml
[tool.pdm.version]
source = "scm"
```
The old names are deprecated at the same time.
> Rename the dynamic verison fields

- README.md
probably a typo, introduced in #100
> docs: dynamic version uses tool.pdm.version, not tool.pdm.build.version

- README.md
The example code on env var `PDM_PEP517_VERSION` does not match the actual design. This typo is fixed by using `PDM_PEP517_SCM_VERSION` instead.
> README.md: Fix Dynamic Version example

- tests/conftest.py
Some of the tests fail on systems that haven't configured git. For example, some downstreams run tests out of a git tree and may not have configured git.
Fixes: https://github.com/pdm-project/pdm-pep517/issues/125
> tests: Configure git for scm tests

- docs/metadata.md
Rename `tag-pattern` to `tag_regex` in the [docs](https://pdm-backend.fming.dev/metadata/#read-from-scm-tag-supporting-git-and-hg).
Since this feature was imported in #148 due to #139, there may be a gap between the origin proposal in the issue and implementation.
> fix: rename tag-pattern to tag_regex in the docs

- docs/build_config.md
I did not search a `namespace` result in PEP 427, is it a typo ?
> doc: correct pep number

- docs/metadata.md
- src/pdm/backend/hooks/version/__init__.py
- src/pdm/backend/hooks/version/scm.py
- src/pdm/backend/utils.py
- tests/fixtures/projects/demo-using-scm/version.py
- tests/test_api.py
> feat: Custom version format for source="scm"

- docs/build_config.md
I had trouble understanding how to declare some wheel data. I thought `include` was a generic key to include stuff. I didn't think it was bound to `$prefix/include` (though in retrospect it makes sense). So I changed the directory name to "headers" to make it more clear. I also added examples, particularly one with `data` and manpages because pipx supports such manpages added as data-files :slightly_smiling_face:
> docs: Add examples to the wheel-data section

- scripts/patches/pyproject_metadata.patch
- src/pdm/backend/_vendor/pyproject_metadata/__init__.py
- src/pdm/backend/_vendor/vendor.txt
- tests/fixtures/projects/demo-metadata-test/pyproject.toml
- tests/test_api.py
> feat(vendors): update pyproject-metadata to 0.8.0rc1

- scripts/patches/pyproject_metadata.patch
- src/pdm/backend/_vendor/pyproject_metadata/__init__.py
- src/pdm/backend/_vendor/vendor.txt
> feat: bump pyproject-metadata to 0.8.0

- CONTRIBUTING.md
- pdm.lock
- pyproject.toml
Given that these dev tools is used to maintain the project, it makes sense to add them as dev dependencies so that contributors don't have to install them manually.
Tools which have been installed:
- black
- isort
- pre-commit
> Add dev tools to pyproject.toml

- docs/metadata.md
- src/pdm/backend/utils.py
- fixed error in document regarding `Get with a specific function` section. More details can be found in #234.
- fixed the issue where single string literal parameters were not correctly handled during parameter parsing.
---
The second fix is necessary because `ast.literal_eval("('example')")` parses the input as a string type instead of a tuple type. 
Fixed #234
> Fixed error about dynamic project version

- .github/workflows/ci.yml
- docs/metadata.md
- pdm.lock
- src/pdm/backend/hooks/version/__init__.py
- src/pdm/backend/hooks/version/scm.py
- src/pdm/backend/utils.py
- tests/pdm/backend/hooks/version/test_scm.py
This PR adds tag_filter as a metadata property which can be used to filter the 
set of tags examined for versioning the project. More details can be found in #219.
The `git` changes in this PR are straightforward. The `hg` changes require a bit more context.
In order to tags, it was necessary to use `hg log` as it provides a `--template` argument to use
with the `latesttag` function. Technically `hg`'s regex is a python style regex, but I didn't think
it prudent to depend on that exact implementation detail. Instead, I refactored the implementation
slightly so that we use `hg log` to extract the current commit and `hg id` is relegated to telling us
if the working tree is dirty.
This is a PR that's stacked on top of #224. For easy of review, I suggest you look at only the
most recent …
> Add tag filter

- src/pdm/backend/hooks/version/scm.py
The error happens when running `pdm install` in a git repo while `git` command does not work as expected but `hg` command is available.
For my case, the permission of `.git` directory is invalid when I try to mount the working directory into a container and then the error happen. Though it is not a critical error, it might be better to handle it well.
traceback for the error:
```
Traceback (most recent call last):
File "/usr/local/bin/pdm", line 8, in <module>
sys.exit(main())
^^^^^^
File "/usr/local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 358, in main
return core.main(args or sys.argv[1:])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/pipx/venvs/pdm/lib/python3.11/site-packages/pdm/core.py", line 276, in main
raise cast(Exception, err).with_traceback(traceback) …
```
> fix: handle unexpected hg repo when parse scm version

- src/pdm/backend/hooks/version/__init__.py
Doesn't makes sense to have a empty version, make easier to treat PDM_BUILD_SCM_VERSION as empty string when you don't have tag information, and instead, use fallback_version.
> Treat PDM_BUILD_SCM_VERSION empty string as unset

- src/pdm/backend/sdist.py
> fix: pdm_build.py added twice in sdist file.

- pyproject.toml
- scripts/patches/pyproject_metadata.patch
- src/pdm/backend/_vendor/pyproject_metadata/__init__.py
- src/pdm/backend/_vendor/pyproject_metadata/constants.py
- src/pdm/backend/_vendor/pyproject_metadata/errors.py
- src/pdm/backend/_vendor/pyproject_metadata/project_table.py
- src/pdm/backend/_vendor/pyproject_metadata/pyproject.py
- src/pdm/backend/_vendor/vendor.txt
Updating to 0.9.0b5. Trying to simplify the patch a bit.
> fix: update to pyproject_metadata 0.9.0b5

- src/pdm/backend/_vendor/pyproject_metadata/__init__.py
- src/pdm/backend/_vendor/pyproject_metadata/constants.py
- src/pdm/backend/_vendor/pyproject_metadata/project_table.py
- src/pdm/backend/_vendor/vendor.txt
> chore: bump validate-pyproject to 0.9.0

- .github/workflows/ci.yml
- docs/index.md
- pdm.lock
- pyproject.toml
- tests/conftest.py
- tests/fixtures/projects/demo-metadata-test/pyproject.toml
- tests/test_api.py
- Drop support for Python 3.8 which [reached EOL](https://devguide.python.org/versions/)
- Properly expose support for Python 3.13
> [!Note] 
> I added `pytest-gitconfig` as a dev dependency to be able to run the test without being prompted for `gpg` at each test (it runs test on a clean config). Plus it provide a ready to use `.gitconfig` (aka. no need to set `user.name` and `user.email`) unless you requires some specific values in the tests
> build(python): update supported Python versions to 3.9 to 3.13

- src/pdm/backend/hooks/version/scm.py
While #197 could be solved in code in the future, I figure this is a reasonable stopgap that improves the error message. Been meaning to send this PR for ages, but only did it now :D.
> Improve diagnostic caused by git incorrectly parsing paths on MSYS2.

- docs/build_config.md
Fix an incorrect path after installed data files
from
```
share/man/man1/project.1 -> $prefix/share/man/man1/project.1
```
to
```
share/man/man1/project.1 -> $prefix/data/share/man/man1/project.1
```
And did some slight refinements for better readability.
> docs: Fix incorrect file paths and refine for better readability

- src/pdm/backend/hooks/version/scm.py
- tests/pdm/backend/hooks/version/test_scm.py
The configuration represents the length commit hashes are abbreviated to. As pdm-backend parses output of git describe to obtain the package version, this configuration affects format of package versions that must be represented with a commit hash part, which is quite surprising and may introduce reproducible issues.
Let's override the core.abbrev with auto and let git decide how long the hash, keeping the format of generated version consistent regardless of value of core.abbrev and fixing failures of
test__get_version_from_scm__returns_default_if_tag_cannot_be_parsed[git] with the git configuration set globally.
Closes: https://github.com/pdm-project/pdm/issues/3490
> fix: Override Git config core.abbrev when reading version from SCM

- docs/metadata.md
Fix: https://github.com/pdm-project/pdm-backend/issues/277#issuecomment-2781781425
Just a tiny docs PR that links to https://github.com/pdm-project/pdm/issues/3385#issuecomment-2632705361 to explain how to use scripts in src layout, or an alternative of putting in a separate scripts package :)
tried to keep it short and sweet, but let me know if this is no good
> Docs: version scripts in src layout

- src/pdm/backend/wheel.py
- tests/test_api.py
A common value for `SOURCE_DATE_EPOCH` is 0, which unfortunately breaks pdm:
```console
$ uv init --build-backend=pdm
$ SOURCE_DATE_EPOCH=0 uv build
File "/Users/branch/.cache/uv/builds-v0/.tmpEkVowp/lib/python3.13/site-packages/pdm/backend/wheel.py", line 52, in <module>
raise ValueError("zipinfo date can't be earlier than 1980")
ValueError: zipinfo date can't be earlier than 1980
```
This clamps to 1980 instead (same as [`setuptools`](https://github.com/pypa/setuptools/blob/c3f486f0f7ebf8fa141dfd7314cbcaba7370db0b/setuptools/_vendor/wheel/wheelfile.py#L40) and [`flit-core`](https://github.com/pypa/flit/blob/13792b5748463f1f5d37bae954e4b44d4ccb341c/flit_core/flit_core/wheel.py#L57-L59). [`poetry`](https://github.com/python-poetry/poetry-core/blob/002aa3e16f98d21645bb9a45f698b55adc40f317/s …
> fix: support a SOURCE_DATE_EPOCH prior to 1980
