pdm-project/pdm-backend

- .github/workflows/ci.yml
- pdm/pep517/metadata.py
- pdm/pep517/scm.py
- pyproject.toml
- setup.cfg
- tests/conftest.py
- tests/fixtures/projects/demo-using-scm/LICENSE
- tests/fixtures/projects/demo-using-scm/README.md
- tests/fixtures/projects/demo-using-scm/foo_module.py
- tests/fixtures/projects/demo-using-scm/pyproject.toml
- tests/test_metadata.py
> New feature: support read version from SCM

- pdm/pep517/scm.py
- pdm/pep517/utils.py
- tests/test_api.py
- tests/test_file_finder.py
- tests/test_metadata.py
- tests/testutils.py
small step along the road to using 'strict' type checking
> fix some 'strict' mypy checks

- tests/test_wheel.py
> Skip test_override_tags_in_wheel_filename on PyPy3

- README.md
> docs: Document writing SCM version to file

- news/105.bugfix.md
- pdm/pep517/base.py
- pdm/pep517/metadata.py
- tests/fixtures/projects/demo-reuse-spec/LICENSES/MPL-2.0.txt
- tests/fixtures/projects/demo-reuse-spec/README.md
- tests/fixtures/projects/demo-reuse-spec/pyproject.toml
- tests/fixtures/projects/demo-reuse-spec/src/foo_module.py
- tests/test_file_finder.py
- tests/test_metadata.py
> fix: handle reuse spec projects

- .github/workflows/ci.yml
- .github/workflows/release.yml
- news/107.bugfix.md
- pdm.lock
- pdm/pep517/editable.py
- tests/test_metadata.py
> read run-setuptools = false for editable build

- pdm/pep517/api.py
This pull request fixes #118 by always creating potential parent directories.
> Support license files located in subdirectories

- pdm.lock
- pyproject.toml
Fixes: https://github.com/pdm-project/pdm-pep517/issues/130
> Add setuptools to dev dependencies

- news/143.feature.md
- pdm/pep517/wheel.py
> feat: support specifying zipinfo date via env var

- setup.cfg
- src/pdm/backend/base.py
- src/pdm/backend/editable.py
- src/pdm/backend/sdist.py
- src/pdm/backend/wheel.py
- tests/test_api.py
> fix: missing files in editable wheel

- src/pdm/backend/editable.py
- src/pdm/backend/sdist.py
- src/pdm/backend/utils.py
- src/pdm/backend/wheel.py
- tests/test_api.py
> fix: normalize the distribution names as the standard

- src/pdm/backend/wheel.py
- tests/test_wheel.py
Fixes #159
- Remove `--py-limited-api` regex check
- Remove abi tag override
- Add unit test cases
> Remove check on py-limited-api

- src/pdm/backend/hooks/version/scm.py
> fix: scm versionning fails when package is not top-level directory

- .gitignore
- src/pdm/backend/base.py
- tests/test_api.py
> fix: cleanup logic to first check config_settings

- src/pdm/backend/hooks/version/scm.py
> fix: raise an error when SCM version can't be determined

- changelogithub.config.json
- docs/api.md
- docs/hooks.md
> doc: Clarify order of `pdm_build_initialize` and `pdm_build_clean`

- docs/build_config.md
- src/pdm/backend/config.py
- src/pdm/backend/hooks/base.py
- src/pdm/backend/wheel.py
- tests/fixtures/projects/demo-package-include/pyproject.toml
- tests/fixtures/projects/demo-package-include/scripts/my_script.sh
- tests/test_api.py
> feat: allow to include files in wheel .data directory

- src/pdm/backend/config.py
> fix: pdm-backend should not normalize names in project metadata

- src/pdm/backend/hooks/setuptools.py
> fix: copytree handle existing dirs

- src/pdm/backend/hooks/version/__init__.py
> feat: Use fallback_version for source = "call"

- pyproject.toml
> Add license file metadata
